import { Injectable, signal } from '@angular/core';
import { environment } from '../../../environment';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class ConvenioService {
  private apiUrl = environment.apiUrl;
  private _convenio = [{
      acuerdo_id: 1,
      nombre: "Convenio1",
      unidad_eject:"ejecutor1",
      mod_conv: "Modalidad1",
      contraparte: 'Empresa123',
      pais: 'Perú',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Activo',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 2,
      nombre: "Convenio1",
      unidad_eject:"ejecutor2",
      mod_conv: "Modalidad2",
      contraparte: 'Empresa456',
      pais: 'Chile',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Vencido',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 3,
      nombre: "Convenio3",
      unidad_eject:"ejecutor3",
      mod_conv: "Modalidad3",
      contraparte: 'Empresa789',
      pais: 'Rusia',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '30/05/2025',
      estado_acuerdo_id: 'Activo',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 4,
      nombre: "Convenio4",
      unidad_eject:"ejecutor4",
      mod_conv: "Modalidad4",
      contraparte: 'Empresa456',
      pais: 'EEUU',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Vencido',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },
    {
      acuerdo_id: 1,
      nombre: "Convenio1",
      unidad_eject:"ejecutor1",
      mod_conv: "Modalidad1",
      contraparte: 'Empresa123',
      pais: 'Perú',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Activo',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 2,
      nombre: "Convenio1",
      unidad_eject:"ejecutor2",
      mod_conv: "Modalidad2",
      contraparte: 'Empresa456',
      pais: 'Chile',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Vencido',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 3,
      nombre: "Convenio3",
      unidad_eject:"ejecutor3",
      mod_conv: "Modalidad3",
      contraparte: 'Empresa789',
      pais: 'Rusia',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '30/05/2025',
      estado_acuerdo_id: 'Activo',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 4,
      nombre: "Convenio4",
      unidad_eject:"ejecutor4",
      mod_conv: "Modalidad4",
      contraparte: 'Empresa456',
      pais: 'EEUU',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Vencido',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 1,
      nombre: "Convenio1",
      unidad_eject:"ejecutor1",
      mod_conv: "Modalidad1",
      contraparte: 'Empresa123',
      pais: 'Perú',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Activo',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 2,
      nombre: "Convenio1",
      unidad_eject:"ejecutor2",
      mod_conv: "Modalidad2",
      contraparte: 'Empresa456',
      pais: 'Chile',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Vencido',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 3,
      nombre: "Convenio3",
      unidad_eject:"ejecutor3",
      mod_conv: "Modalidad3",
      contraparte: 'Empresa789',
      pais: 'Rusia',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '30/05/2025',
      estado_acuerdo_id: 'Activo',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 4,
      nombre: "Convenio4",
      unidad_eject:"ejecutor4",
      mod_conv: "Modalidad4",
      contraparte: 'Empresa456',
      pais: 'EEUU',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Vencido',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 1,
      nombre: "Convenio1",
      unidad_eject:"ejecutor1",
      mod_conv: "Modalidad1",
      contraparte: 'Empresa123',
      pais: 'Perú',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Activo',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 2,
      nombre: "Convenio1",
      unidad_eject:"ejecutor2",
      mod_conv: "Modalidad2",
      contraparte: 'Empresa456',
      pais: 'Chile',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Vencido',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 3,
      nombre: "Convenio3",
      unidad_eject:"ejecutor3",
      mod_conv: "Modalidad3",
      contraparte: 'Empresa789',
      pais: 'Rusia',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '30/05/2025',
      estado_acuerdo_id: 'Activo',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 4,
      nombre: "Convenio4",
      unidad_eject:"ejecutor4",
      mod_conv: "Modalidad4",
      contraparte: 'Empresa456',
      pais: 'EEUU',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Vencido',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 1,
      nombre: "Convenio1",
      unidad_eject:"ejecutor1",
      mod_conv: "Modalidad1",
      contraparte: 'Empresa123',
      pais: 'Perú',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Activo',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 2,
      nombre: "Convenio1",
      unidad_eject:"ejecutor2",
      mod_conv: "Modalidad2",
      contraparte: 'Empresa456',
      pais: 'Chile',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Vencido',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 3,
      nombre: "Convenio3",
      unidad_eject:"ejecutor3",
      mod_conv: "Modalidad3",
      contraparte: 'Empresa789',
      pais: 'Rusia',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '30/05/2025',
      estado_acuerdo_id: 'Activo',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 4,
      nombre: "Convenio4",
      unidad_eject:"ejecutor4",
      mod_conv: "Modalidad4",
      contraparte: 'Empresa456',
      pais: 'EEUU',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Vencido',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 1,
      nombre: "Convenio1",
      unidad_eject:"ejecutor1",
      mod_conv: "Modalidad1",
      contraparte: 'Empresa123',
      pais: 'Perú',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Activo',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 2,
      nombre: "Convenio1",
      unidad_eject:"ejecutor2",
      mod_conv: "Modalidad2",
      contraparte: 'Empresa456',
      pais: 'Chile',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Vencido',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 3,
      nombre: "Convenio3",
      unidad_eject:"ejecutor3",
      mod_conv: "Modalidad3",
      contraparte: 'Empresa789',
      pais: 'Rusia',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '30/05/2025',
      estado_acuerdo_id: 'Activo',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    },{
      acuerdo_id: 4,
      nombre: "Convenio4",
      unidad_eject:"ejecutor4",
      mod_conv: "Modalidad4",
      contraparte: 'Empresa456',
      pais: 'EEUU',
      fecha_subscripcion: '01/01/2000',
      fecha_inicio: '01/02/2000',
      fecha_fin: '01/01/2025',
      estado_acuerdo_id: 'Vencido',
      planTrabajo: 'Plan1',
      adjunto: 'Adjunto1',
    }

  ]

  constructor(private http: HttpClient) {  }

  getConvenios() {
    return this._convenio
  }

  setConvenios(convenios: any) {
    this._convenio = convenios;
  }
}
